In [1]:
import numpy as np
import pandas as pd

In [2]:
def choice_home(home_number):
    if home_number==1:
        return ["HHHHHHHHHHHHHHH",
                "HFFFFFFHFFHHHFH",
                "HFFHHFFHFFFFHFH",
                "HFFHHFFHFFFFHFH",
                "HFFFFFFHFFFFFFH",
                "HHHHHHFFFHHHHHH",
                "HFFFFHFFFHFFFFH",
                "HFFFFFFFFHFHHFH",
                "HFFFFHFFFFFFHFH",
                "HHHHHHFFFHFFFFH",
                "HFFFFHFFFHHHHHH",
                "HFFFFFFFFHFFFFH",
                "HHHHHHFFFHFFHFH",
                "HSFFFFFFFFFHHFH",
                "HHHHHHHHHHHHHHH"]

In [3]:
class Robot:
    np.random.seed(2)
    def __init__(self, home):
        self.gamma=0.9 #feedback oranı
        self.alpha=0.1 #öğrenme oranı
        self.epsilon=0.9 #
        self.max_episodes=100
        self.actions=['left','right','up','down']
        self.home = home
        self.x, self.y = self.create_robot_loc()
        self.map=self.create_map()
        self.update_map([self.y,self.x])

    def update_map(self,locs):
        self.map[locs[0],locs[1]]=1
    def create_map(self):
        return np.zeros([len(home),len(home[0])],int)
    def create_robot_loc(self):
        x=0
        y=0
        for line in home:
            for state in line:
                if (state == 'S'):
                    return x,y
                    break
                x+=1
            x=0
            y+=1
        
    def show_map(self):
        print(self.map)
        
    def get_loc(self):
        return self.y,self.x
        
    def set_loc(self,y,x):
        self.x=x
        self.y=y
        
    def act_feedback(self,act):
        y,x=self.get_loc()
        if act=='right':
            if home[y][x+1]!='H':
                if self.map[y][x+1]==0:
                    self.map[y][x+1]=1
                    self.set_loc(y,x+1)
                    R=2
                else:
                    R=-10 
            else:
                R=-1
        if act=='left':
            if home[y][x-1]!='H':
                if self.map[y][x-1]==0:
                    self.map[y][x-1]=1
                    self.set_loc(y,x-1)
                    R=2
                else:
                    R=-10 
            else:
                R=-1 
        if act=='up':
            if home[y-1][x]!='H':
                if self.map[y-1][x]==0:
                    self.map[y-1][x]=1
                    self.set_loc(y-1,x)
                    R=2
                else:
                    R=-10 
            else:
                R=-1
        if act=='down':
            if home[y+1][x]!='H':
                if self.map[y+1][x]==0:
                    self.map[y+1][x]=1
                    self.set_loc(y+1,x)
                    R=2
                else:
                    R=-10 
            else:
                R=-1
        return R
       
    def choise_act(self,Table):
        state_acts=Table.loc[self.get_loc()]
        if (np.random.uniform() > self.epsilon) or (state_acts==0).all():
            act_name = np.random.choice(self.actions)
        else:
            act_name=state_acts.idxmax()
        return act_name
        
    def qTable(self,states,act):
        q_table = pd.DataFrame(np.zeros((len(states), len(self.actions)))
                               ,index=pd.MultiIndex.from_tuples(states, names=['Row', 'Column']),columns=self.actions)
        return q_table
        
    def learn(self):
        table=self.qTable(states,self.actions)
        self.set_loc(self.create_robot_loc()[1],self.create_robot_loc()[0])
        totalR=cal_home(len(home))
        for ep in range(self.max_episodes):
            oldState=self.get_loc()
            Done=True
            k=0
            while Done==True:
                act=self.choise_act(table)
                R = self.act_feedback(act)
                k+=R
                if totalR-20<k and k<totalR+20:
                    target= R
                    Done=False
                else :
                    target = R+self.gamma*table.loc[oldState].max()
                predict=table.loc[oldState,act]
                table.loc[oldState,act]=self.alpha*(target-predict)
        self.show_map()
        

In [4]:
home=choice_home(1)
states = [(i, j) for i in range(len(home)) for j in range(len(home[0]))]
robot1=Robot(home)


In [5]:
def cal_home(l):
     H=l*4-4+63+4*(l-15)
     F=l*l-H
     constFail=25
     total=(F*1)-(H*1)-(constFail*1)
     return total

In [6]:
robot1.learn()

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
